### ISSUE TITLE
strange things in history

### ISSUE THREAD

**Issue by gacopl** [nemosminer/NemosMiner-v2.2#22]
I've been running this version less than 20 hours and i get this in history, thousands of days etc:

0,00 PH/s 456442 Days 02 Hours 01 Minutes 46 Times Bin\NVIDIA-skunk\ccminerskunk.exe -a skunk -o stratum+tcp://mine.zpool.ca:8433 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC -i 24
0,00 PH/s 00 Days 01 Hours 59 Minutes     29 Times Bin\NVIDIA-ccminer-2.2\ccminer-x64.exe -a tribus -o stratum+tcp://mine.zpool.ca:8533 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 152147 Days 19 Hours 32 Minutes 7 Times  Bin\NVIDIA-Alexis78\ccminer.exe -a nist5 -o stratum+tcp://mine.zpool.ca:3833 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 00 Days 00 Hours 03 Minutes     Once     Bin\NVIDIA-CcminerKlaust\ccminer.exe -a groestl -o stratum+tcp://mine.zpool.ca:5333 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 00 Days 00 Hours 09 Minutes     3 Times  Bin\NVIDIA-TPruvot\ccminer-x64.exe -a hmq1725 -o stratum+tcp://mine.zpool.ca:3747 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 152147 Days 13 Hours 16 Minutes 11 Times Bin\NVIDIA-Alexis78\ccminer.exe -a x17 -o stratum+tcp://mine.zpool.ca:3737 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC -i 21
0,00 PH/s 00 Days 02 Hours 04 Minutes     16 Times Bin\NVIDIA-Alexis78\ccminer.exe -a blake2s -o stratum+tcp://mine.zpool.ca:5766 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 152147 Days 06 Hours 14 Minutes 3 Times  Bin\NVIDIA-TPruvot\ccminer-x64.exe -a timetravel -o stratum+tcp://mine.zpool.ca:3555 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 00 Days 00 Hours 07 Minutes     4 Times  Bin\NVIDIA-Alexis78cuda8.0\ccminer_x11gost.exe -a sib -o stratum+tcp://mine.zpool.ca:5033 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC -i 21
0,00 PH/s 00 Days 00 Hours 20 Minutes     7 Times  Bin\NVIDIA-Alexis78\ccminer.exe -a c11 -o stratum+tcp://mine.zpool.ca:3573 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC -i 21
0,00 PH/s 00 Days 09 Hours 20 Minutes     Once     Bin\NVIDIA-Alexis78\ccminer.exe -a lyra2v2 -o stratum+tcp://mine.zpool.ca:4533 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c=BTC
0,00 PH/s 00 Days 00 Hours 03 Minutes     Once     Bin\NVIDIA-Alexis78\ccminer.exe -a blakecoin -o stratum+tcp://mine.zpool.ca:5743 -u 1Cnb8ievaqvsJwg5VL5xiss2EzGLYu1HD6 -p ID=NemosMiner-v2.0.9,c

**Comment by nemosminer** [comment]
yip its algud "i know about it, i'll sort it soon" doesn't affect anything mining related just stat's...

**Comment by gacopl** [comment]
thanks, please also think about the gpu switch, as right now when i want to play on one of my cards i have to change to other software where i can mine with cards specified and play at the same time :). And again different types of cards are better in different algos, so it would be wise to fire up separate instances and benchmark them separately, so each type of card would mine the best algo for them
