### ISSUE TITLE
static port EWBF port 2142 

### ISSUE THREAD

**Issue by viatoro** [nemosminer/NemosMiner-v2.2#39]
Arguments = "--api --server $($Pools.(Get-Algorithm($_)).Host) --port 2142 --fee 0 --solver 0 --eexit 1 --user $($Pools.(Get-Algorithm($_)).User) --pass $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"
        

Arguments = "--api --server $($Pools.(Get-Algorithm($_)).Host) --port $($Pools.(Get-Algorithm($_)).Port) --fee 0 --solver 0 --eexit 1 --user $($Pools.(Get-Algorithm($_)).User) --pass $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"

**Comment by nemosminer** [comment]
thankyou
