### ISSUE TITLE
If any wants to have less frequent switch

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.2#40]
If any wants to have less frequent switch you should change DecayBase in the main miner.ps1 (nemosminer.ps1, multiminer.ps1,....)

from:
Code:
$DecayBase = 1 - 0.1 
to:
Code:
$DecayBase = 1 - 0.01 

Quote from @aaronsace  of multiminer on github:
Quote
It's the percentage that it decreases the switching threshold. It will switch less and when it does they are more likely to be stable coins compared to just increasing the interval.

**Comment by asktomsk** [comment]
I tried to set `$DecayBase = 1 - 0.01` and it was mining Lbry (6th from the top at that moment) for 15 minutes. I stopped everything and reverted that change back to `$DecayBase = 1 - 0.1`

**Comment by aaronsace** [comment]
@asktomsk This is to reduce the switching to longer than 15 minutes. 

@nemosminer For this to work correctly the margins of error need to be correct. The stats are currently initialized at +/- 50%. I am going to amend the stats function so the initial value is not needed but for now changing the initial value to +/- 10% would help. 

`Week_Fluctuation = 1 / 2` to 'Week_Fluctuation = 1 / 10

**Comment by nemosminer** [comment]
i havn't changed anything yet..  still testing

**Comment by jt42jt** [comment]
Is there a way to have the miner window not grab focus when it starts up?

**Comment by aaronsace** [comment]
@jt42jt It's annoying when watching YouTube. Other than having no window, I'm not sure there is. 
If there is a way, I'd like to know.

**Comment by UselessGuru** [comment]
@aaronsace 
> Other than having no window, I'm not sure there is.
If there is a way, I'd like to know.

I am experimenting with this:
[https://github.com/FuzzySecurity/PowerShell-Suite/blob/master/Invoke-CreateProcess.ps1](url)
