### ISSUE TITLE
2.1 vs 2.2

### ISSUE THREAD

**Issue by Pititul** [nemosminer/NemosMiner-v2.2#51]
I started with 2.1 in the release and moved to 2.2 in code (master)... 2.1 seems to show better profit than 2.2 for some reasons. I don't want to miss out new improvements on the new version, will it get better if I keep mining? 

I have 1070 x 3.

**Comment by nemosminer** [comment]
2.2 is still being worked on id suggest running 2.1 until i do final release of 2.2
