### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by jjude80** [nemosminer/NemosMiner-v2.2#55]
Where is the benchmarking length determined?  I want it to run longer per algorithm.

**Comment by nemosminer** [comment]
edit start.bat change -Interval 60 

defualf 60 = 60 seconds before checking miner hashrate you can change this to any number

eg: 

-Interval 90
-Interval 120
-Interval 240 etc..

**Comment by Weeeishy** [comment]
Hi,

Sorry for commenting on this closed issue, but I've noticed that when I set it for an example for 300 seconds, it just ignores that and benchmarks for long and random time like above 20 minutes which I think it's not supposed to do that? I'm using zpool24hr.bat with my interval set to 300. If you need other information, then please let me know. 

Thanks!
