### ISSUE TITLE
incorrect coded character set

### ISSUE THREAD

**Issue by enochi** [nemosminer/NemosMiner-v2.2#56]
I download v2.2 version with git clone,but get a wrong message with:
kecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s -Donate 5
所在位置 D:\Users\Administrator\Desktop\m\bak\NemosMiner-v2.2\NemosMiner-v2.2.ps1:230 字符: 338
+ ... Regex = 慯(?+ (($_.Type | ForEach {[Regex]::Escape($_)}) -join 搢? + ?$ ...
+                                                                  ~
必须在“-join”运算符后面提供一个值表达式。
所在位置 D:\Users\Administrator\Desktop\m\bak\NemosMiner-v2.2\NemosMiner-v2.2.ps1:230 字符: 339
+ ... ex = 慯(?+ (($_.Type | ForEach {[Regex]::Escape($_)}) -join 搢? + ?$? $ ...
+                                                                ~~
I know it's related to my character set,but I used chcp changed to utf-8 still not working.
please help. thanks.

**Comment by nemosminer** [comment]
im testing v2.2 most current master on 6 different rigs im not seeing that issue at all
