### ISSUE TITLE
Failure to populate pool URL during first run

### ISSUE THREAD

**Issue by JerichoJones** [nemosminer/NemosMiner-v2.2#64]
![image](https://user-images.githubusercontent.com/13205729/32681772-2eb4881e-c63f-11e7-9fed-746de406b491.png)

**Comment by nemosminer** [comment]
my test rigs are fine... is it still happing? for you

**Comment by JerichoJones** [comment]
It seems to have finished benchmarking successfully. I guess it recovered from the error.
