### ISSUE TITLE
the miner freezes at one alogrithm 

### ISSUE THREAD

**Issue by bac203** [nemosminer/NemosMiner-v2.2#65]
i mine with the last  version somtimes when my  internet  connection  is slow  or cutdown for  a moment the update request will get stuck and the miner  will no longer  update to mine the most  profitable algorithm . can you  add  time-out for the request 
-at least that's what i think it's the probleme

**Comment by nemosminer** [comment]
if connection is lost it will automatically check every 10 secs to see if connection is there and re connect
