### ISSUE TITLE
CCminer stoped working

### ISSUE THREAD

**Issue by Citymix** [nemosminer/NemosMiner-v2.2#67]
Hello there
I'm having some troubles using your miner, 1st of all in older versions when the window was poping up by saying "ccminer stopped working" the miner itself could close the window and automatically switch to other coin to mine, but now with this new updates whenever the "ccminer stopped working" window is popping up and it won't close anymore and will stick there as long as I manually close the window :( 

I'm using 8 GPU's 1080ti.

**Comment by thebitbrine** [comment]
Same problem :(

**Comment by nemosminer** [comment]
i have only tested with up2 6 gus any more i can't guarantee will work
