### ISSUE TITLE
Error message when running script and reboot windows many time(reboot 10-20 times/day)

### ISSUE THREAD

**Issue by peerawits** [nemosminer/NemosMiner-v2.2#69]
ConvertFrom-Json : Invalid JSON primitive: .
At C:\NemosMiner-v2.2-master\Include.ps1:125 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by beggsdl** [comment]
I'm not sure if I should ask this here or not, but what was the cause of this JSON error?  I'm receiving it when running v2.4.1 but not when running v2.3c-Beta.   Thanks
