### ISSUE TITLE
profitability not updating

### ISSUE THREAD

**Issue by maxgamurar** [nemosminer/NemosMiner-v2.2#71]
Hello!
I was mining for many hours. Main table with profitability is not getting updated.
I had to restart main script to get updated table.

**Comment by nemosminer** [comment]
zpool?

**Comment by maxgamurar** [comment]
miningpoolhub

**Comment by maxgamurar** [comment]
happened today again, profitability for 1080 ti was set to skein algo, which is worst profitable.

**Comment by nemosminer** [comment]
can you send me a screen shot of it running skein with the main window open so i can see:

like this: https://imgur.com/a/UV37e

Regards
Nemo

**Comment by maxgamurar** [comment]
@nemosminer please check 2 images, 1 from miner, 2nd from mph profit list.
![mhp_skein_actual](https://user-images.githubusercontent.com/3941277/33805188-12775f68-dde7-11e7-90c5-a290366c0740.PNG)
![mph_nemos_skein](https://user-images.githubusercontent.com/3941277/33805189-12ae4456-dde7-11e7-8aa0-43369adf1418.png)

**Comment by nemosminer** [comment]
those price are correct

**Comment by nemosminer** [comment]
2nd from mph profit list. is a general Nvidia profit list.......

1 from miner,  is accurate to suit your cards rigs (my miner profit table is correct)

no Issue Here close
