### ISSUE TITLE
lyra2v2

### ISSUE THREAD

**Issue by JhonJhonny** [nemosminer/NemosMiner-v2.2#73]
seems like i can't add some algos like lyra2v2 for example, which are the algo supported to mine with nemosminer? thanks in advance

**Comment by nemosminer** [comment]
..... lyra2v2  is enabled on every pool...

**Comment by nemosminer** [comment]
current supported algos:

poly,hsr,phi,keccak,xevan,veltor,lyra2z,skunk,tribus,c11,x11evo,lbry,skein,equihash,groestl,timetravel,sib,bitcore,x17,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s

**Comment by JhonJhonny** [comment]
sorry, the first 1 was the stupidest question xD, i was writing in the bat file lyra2v2 instead of lyra2RE2.managed to find out by my self. btw thanks for the list of algorithms.
are you planning on adding other algos or adding other miners in the near future?

**Comment by nemosminer** [comment]
yes
